### PR TITLE
Go through the TODO list

### PR DESCRIPTION
**Pull request by Elv13**
Ok, here is an early version of your project "rewrite". Most of the code has been refactored to introduce a QAbstractItemModel based "data layer". Dragging socket create QMimeData. The "QObjectNode" (now implicit) are now creating their own model and adding them to the "master model".

New features:

 * MetaType support: Connections are now aware of their base type and this is used in the GUI to hide the invalid sockets when drag&dropping.
 * Socket and edge colors based on the type

Is it done?:

No, there is more TODO in the code now than there was when I started.

* It doesn't support models that "lose" rows over time (the code skeleton is there, but with TODO and FIXME).
* If a QModelIndex as both a source and a sink, then only one of them can is synchronized.
* Some classes are not refactored yet.
* There is still some exposed private classes that could be merged into their .cpp
* There is still coupling between the data layer and the view that isn't "pure Qt Model/View" yet.
* The QAbstractItemView isn't implemented
* The QStyleSheet support isn't implemented
* It isn't exposed to QML properly.
* The README and examples are not up to date
* Some of the code path could be further optimized
* There is probably some (many) memory leaks left

I don't know if you want/plan to merge this. It isn't "finished" nor is it close to being "finished". As I said, once it "is", I would like to see this upstreamed to Qt.

I will fix the bugs once I hit them, but I would say this is now "good enough" for my project for now. So the development pace will go down.

### CODE REVIEW

**Comment by nwaniek** [comment]
Thanks for the amazing work! I will check it and merge as soon as possible.

**Comment by Elv13** [comment]
I pushed yet more commits. It is now possible to meta-serialize the node editor to JSON. The code for this is

``` c++
void ProxyNodeFactoryAdapter::serialize(QIODevice *dev) const
{
    QJsonObject session;

    const auto cats = m_slCategory;

    auto sConn = [](QJsonArray& ret, QAbstractItemModel* m, const QString& name) {
        for(int i =0; i < m->rowCount(); i++) {
            const auto edgeI  = m->index(i,1);

            // Only serialize when there is a connection
            if ((!edgeI.data().canConvert<int>())
                continue;

            const auto sockI  = m->index(i,0);
            const auto rsockI = m->index(i,2);
            const auto rnode  = m->index(i,3);
            const auto nodeid = rnode.data(Qt::UserRole).toString();

            Q_ASSERT(!nodeid.isEmpty());

            QJsonObject o;

            o[ "direction"    ] = name;
            o[ "own_socket"   ] = sockI.data ().toString();
            o[ "other_socket" ] = rsockI.data().toString();
            o[ "id"           ] = edgeI.data ().toInt();
            o[ "other_node"   ] = nodeid;

            ret.append(o);
        }
    };

    QJsonArray levelArray;

    for (const auto& cat : cats) {
        const auto types = cat->m_lTypes;
        for (const auto& type : types) {
            const auto& elems = type->m_lInstances;
            for (const auto& elem : elems) {
                QJsonObject data;
                elem.second->write(data);

                QJsonObject node;
                node["data"] = data;

                const auto nodeW = elem.first;
                const auto sinkModel   = m_pNodeW->sinkSocketModel(nodeW->index());
                const auto sourceModel = m_pNodeW->sourceSocketModel(nodeW->index());

                QJsonObject widget;
                widget["x"    ] = nodeW->graphicsItem()->pos().x();
                widget["y"    ] = nodeW->graphicsItem()->pos().y();
                widget["title"] = nodeW->title();
                widget["UID"  ] = nodeW->index().data(Qt::UserRole).toString();

                QJsonArray conns;
                sConn(conns, sourceModel, QStringLiteral("source"));
                sConn(conns, sinkModel  , QStringLiteral("sink"  ));
                widget["connections"] = conns;

                node["widget"] = widget;

                levelArray.append(node);
            }
        }
    }

    session["nodes"] = levelArray;

    dev->write(QJsonDocument(session).toJson());
}

void ProxyNodeFactoryAdapter::load(const QByteArray& data)
{
    QJsonDocument loadDoc(QJsonDocument::fromJson(data));

    const auto obj = loadDoc.object();

    const auto nodes = obj["nodes"].toArray();

    QHash<QString, GraphicsNode*> fromHash;
    QHash<GraphicsNode*, QString> toHash;

    typedef struct {
        int           id;
        bool          isSource;
        GraphicsNode* node;
        QString       ownS;
        QString       otherS;
        QString       otherN;
    } Conn;

    QMap<int, Conn*> connections;

    auto loadConnections = [&connections](const QJsonArray& a, GraphicsNode* s) {
        for (int cId = 0; cId < a.size(); ++cId) {
            const auto c = a[cId].toObject();
            bool isSource = c["direction"] == QLatin1String("source");
            int connId = c["id"].toInt() * (isSource ? 1 : -1);

            connections.insert(connId, new Conn {
                /* id;      */ connId,
                /* isSource;*/ isSource,
                /* node;    */ s,
                /* ownS;    */ c["own_socket"  ].toString(),
                /* otherS;  */ c["other_socket"].toString(),
                /* otherN;  */ c["other_node"  ].toString(),
            });
        }
    };

    for (int nodeId = 0; nodeId < nodes.size(); ++nodeId) {
        const QJsonObject node = nodes[nodeId].toObject();

        const auto widget = node[ "widget" ].toObject();
        const auto data   = node[ "data"   ].toObject();

        const QString type = data["id"].toString();

        if (m_hIdToType[type]) {
            const auto uid = widget["UID"].toString();

            auto pair = addToSceneFromMetaObject(m_hIdToType[type]->m_spMetaObj, uid);
            pair.second->read(data);

            auto nodeW = pair.first;

            const auto sinkModel   = nodeW->sinkModel();
            const auto sourceModel = nodeW->sourceModel();

            nodeW->graphicsItem()->setPos({
                widget["x"].toInt(),
                widget["y"].toInt()
            });

            if (!widget["title"].toString().isEmpty())
                nodeW->setTitle(widget["title"].toString());

            loadConnections(widget["connections"].toArray(), nodeW);


            if (uid.isEmpty()) {
                qWarning() << "Failed to properly load a node, some links may be missing";
                continue;
            }

            fromHash[uid] = nodeW;
            toHash[nodeW] = uid;

            if (auto m = const_cast<QAbstractItemModel*>(nodeW->index().model()))
                m->setData(nodeW->index(), uid, Qt::UserRole);
        }
    }

    auto edgeM = m_pNodeW->edgeModel();

    // Add the edges
    for (auto i = connections.constBegin(); i != connections.constEnd(); ++i) {
        const auto conn = i.value();

        if (conn->id >= 0) { // Sources
            // Validate symmetry
            auto otherconn = connections[-i.key()];
            Q_ASSERT(otherconn && otherconn != conn);
            Q_ASSERT(toHash[otherconn->node] == conn->otherN);
            Q_ASSERT(toHash[conn->node ] == otherconn->otherN);

            const int row = edgeM->rowCount() -1;
            const auto srcSock  = conn->node->socketIndex(conn->ownS);
            const auto sinkSock = otherconn->node->socketIndex(otherconn->ownS);

            if ((!srcSock.isValid()) || (!sinkSock.isValid())) {
                qWarning() << "Failed to restore the connection between"
                    << conn->node->title() << ':' << conn->ownS << "and"
                    << otherconn->node->title() << ':' << otherconn->ownS;
                continue;
            }

            edgeM->setData(
                edgeM->index(row, 0),
                srcSock,
                QReactiveProxyModel::ConnectionsRoles::SOURCE_INDEX
            );
            edgeM->setData(
                edgeM->index(row, 2),
                sinkSock,
                QReactiveProxyModel::ConnectionsRoles::DESTINATION_INDEX
            );
        }

        delete conn;
    }
}

void ProxyNodeFactoryAdapter::load(QIODevice *dev)
{
    const QByteArray data = dev->readAll();
    load(data);
}
```

**Comment by nwaniek** [comment]
Again, amazing work! 

I checked and examined your previous commits and will now go ahead and directly merge all your changes. That said, I found some (minor issues) in the previous commits
- qAsConst is (officially) not defined for rvalue references and had to be replaced. I will double check if this is still the case later. 
- There is an error in qobjectmodel.cpp:406. C++ ISO 8.5.4 does not allow type narrowing in list initialization. 

I will submit fixes and check all other warnings as soon as I have access to my private notebook.

**Comment by Elv13** [comment]
Thanks. I guess the API will eventually have to break again, but for now it "works for me". Also, the code could be cleaned/simplified further. Then again, it is not like if I could !fixup and rebase those changes back into that PR anyway, there would be too many conflicts. At least, from now on, it will be possible to do "clean" commits again now that the refactoring is over. It still leave some parts of Frankenstein monster kind of hybrid camelCase/underscore and space/tabs. That can be fixed when the `QAbstractItemView` will replace the current GraphicsView/GraphicsScene. Then, all the leaks/clang/clazy/krazy2/scan-build/valgrind issues have to be fixed.

**Comment by nwaniek** [comment]
Sounds reasonable. Btw. I will migrate the example(s) to a separate project soon, to have the library code completely independent of it.

**Comment by Elv13** [comment]
Ok, they are currently broken anyway. I am not totally done with the CMakeLists too, while it is currently possible to do `add_directory` from a parent project, there is no `find_package` support, no ABI versioning, no "without .h" header symlink, no "include directory", no `Q_DECL_EXPORT` and a few other missing features to turn it into a "real" library.

**Pull request merged**
